Refactor/cleanup
bcc-code/brunstadtv-app pull request #82
Opened 2023-02-14 11:04 UTC by andreasgan

2023-02-14 11:07 UTC, andreasgan commented
@eliezerben can you run through this when you are back? I ran through all the lint errors.

I recommend ignoring whitespace when reviewing:
![image](https://user-images.githubusercontent.com/727125/218718937-372a6784-3045-45d0-847f-3c908e2ba22d.png)

2023-02-14 11:07 UTC, andreasgan commented
Just look for anything obvious wrong etc

2023-02-15 10:17 UTC, eliezerben requested changes

2023-02-15 10:52 UTC, eliezerben approved these changes

2023-02-15 12:28 UTC, merged