Feat/survey
bcc-code/brunstadtv-app pull request #98
Opened 2023-03-20 16:11 UTC by eliezerben

2023-03-21 11:01 UTC, andreasgan requested changes

2023-03-22 08:44 UTC, andreasgan requested changes

2023-03-22 15:57 UTC, eliezerben commented on lib/components/surveys/rating_bar.dart
> +        children: List.generate(5 * 2 - 1, (index) {
Updated to usefull width.

2023-03-23 08:25 UTC, andreasgan commented on lib/providers/surveys.dart
> +class CompletedSurveysNotifier extends AsyncNotifier<List<CompletedSurvey>> {
Cool, didnt know about this one

2023-03-23 08:33 UTC, andreasgan approved these changes

2023-03-23 08:34 UTC, andreasgan commented on lib/components/prompts/prompts.dart
> +    final completedSurveys = ref.watch(completedSurveysProvider).valueOrNull ?? [];
@eliezerben I updated it

2023-03-23 08:34 UTC, merged